package com.user.mngmnt.enums;

public enum Action {
	PAYMENT_CREDIT, 
	PAYMENT_DEBIT, 
	SET_TOP_BOX_REMOVED, 
	SET_TOP_BOX_ADDED, 
	PACK_CHANGE, 
	PACK_REMOVE, 
	PACK_ADD,
	CHANNEL_ADD, 
	CHANNEL_REMOVE,
	OPENING_BALANCE,
	DISCOUNT,
	PAYMENT_START_DISCOUNT,
	CHANNEL_PAYMENT_START_DISCOUNT,
	CHANNEL_REMOVE_DISCOUNT,
	ADD_CHANNEL,
	REMOVE_CHANNEL,
	SET_TOP_BOX_REMOVE,
	SET_TOP_BOX_DEACTIVE,
	SET_TOP_BOX_ACTIVE,
	ADDITIONAL_DISCOUNT,
	ADDITIONAL_CHARGE;
}
